### ISSUE TITLE
Static publisher between the Vicon frame and the real robot.

### ISSUE THREAD

**Issue by TomasMerva** [INTERACT-tud-amr/dinova#12]
We need to implement and primarily figure out the transformation between the Vicon dingo frame and the real robot.

**Comment by TomasMerva** [comment]
The same issue is also with the lidar and dingo.

**Comment by maxspahn** [comment]
A hot fix at runtime can be
```bash
rosrun tf static_transform_publisher 0 0 0 0 0 0 /dingo2 /base_link 0.01
```

**Comment by TomasMerva** [comment]
We can add it to the bringup launch file for now
