### ISSUE TITLE
Missing file with lidar example

### ISSUE THREAD

**Issue by saraybakker1** [INTERACT-tud-amr/dinova#13]
Hi Tomas,

I am currently trying to run the example code from the dingo_description package, and I think this launch file is missing/removed and/or not adapted in the readme:  
roslaunch dingo_kinova_description visualize_dingo_omni.launch lidar:=true dingo_real_urdf:=false

**Comment by TomasMerva** [comment]
Fixed with e6ef4c8 . The `readme.md` file was outdated. Thank you
