### ISSUE TITLE
BUG: Wrong velocities when using the dinova state publisher

### ISSUE THREAD

**Issue by maxspahn** [INTERACT-tud-amr/dinova#21]
I found a bug in the omni_states_publisher.

The velocity data is directly taken from the odometry. However, the odometry is in robot_frame where the omni_states must be in world frame. See code snippet.

https://github.com/INTERACT-tud-amr/dinova/blob/2d2f340e821bf7dbeb69476fa8539b961d338e11/dinova_control/scripts/dinova_state_publisher.py#L110-L134

**Comment by maxspahn** [comment]
This also applies to the recently merged dingo_state publisher: 

https://github.com/INTERACT-tud-amr/dinova/blob/2d2f340e821bf7dbeb69476fa8539b961d338e11/dinova_control/scripts/dingo_state_publisher.py#L66-L71

**Comment by TomasMerva** [comment]
Fixed in [7101100](https://github.com/INTERACT-tud-amr/dinova/commit/710110030d18cff67902ba9b31036ef604043dc7)
