### ISSUE TITLE
Bring in the second Dinova

### ISSUE THREAD

**Issue by maxspahn** [INTERACT-tud-amr/dinova#25]
In order to have a nice demo, we must bring in the second dinova to see where issues appear.

**Comment by maxspahn** [comment]
The usage of namespaces should allow that.

In order to have a central ros-master, we need either an external laptop or the two robots will be treated differently.

The first option is preferred.

We expect some issues on topic names, see https://wiki.ros.org/Names

**Comment by TomasMerva** [comment]
This has been solved except for one bug #33 . Closing this issue
