### ISSUE TITLE
Adding the lidar as optional to the dingo.xacro

### ISSUE THREAD

**Issue by maxspahn** [INTERACT-tud-amr/dinova#3]
Luzia wanted to add a lidar to the robot. 
That would be highly benifical to everyone.

- [x] We have to add the lidar to the robot descriptions
- [x] the drivers should be in here as well

**Comment by TomasMerva** [comment]
Commit 930a34a0e2fbea1f23b552ed587599a8a702e8a1: Lidar has been added to the real dingo urdf file as an argument.

**Comment by maxspahn** [comment]
The urdf file has to be changed to account for the increased hight of the arm.
